export enum GameActions {
  CREATE_GAME = 'CREATE_GAME',
  RESET = 'RESET',
  LOAD_GAME = 'LOAD_GAME',
  ADD_PLAYER = 'ADD_PLAYER',
  SET_ME = 'SET_ME',
  UPDATE_PLAYER = 'UPDATE_PLAYER',
  UPDATE_ARROWS = 'UPDATE_ARROWS',
  MOVE = 'MOVE',
}

export enum GameMutations {
  SET_GAME = 'SET_GAME',
  SET_PLAYERS = 'SET_PLAYERS',
  SET_ME = 'SET_ME',
  SET_OBJECT_TILES = 'SET_OBJECT_TILES',
  SET_ARROWS = 'SET_ARROWS',
}
