export enum EErrorCode {
  ACTIONS_LOCKED = 'ACTIONS_LOCKED',
  ACTIVE_ROUND_EXISTS = 'ACTIVE_ROUND_EXISTS',
  GAME_FULL = 'GAME_FULL',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  MAX_ACTIONS = 'MAX_ACTIONS',
  NETWORK_ERROR = 'NETWORK_ERROR',
  NO_ACTIVE_ROUND = 'NO_ACTIVE_ROUND',
  PLAYER_NOT_OWNER = 'PLAYER_NOT_OWNER',
  ROUND_OVER = 'ROUND_OVER',
  ROUND_STARTED = 'ROUND_STARTED',
}
